name = "wlroots"
version = "main"
summary = "wlroots package"
license = "TBD"
deps = []

[src]
type = "git"
url = ""
sha256 = ""

[build]
system = "meson"

[scripts]
patch = "patch.sh"
build = "build.sh"
install = "install.sh"
check = "check.sh"
