name = "example"
version = "0.0.2"
summary = "This is a example"
license = "MIT"

deps = ["m4"]

[src]
type = "url"
url = "https://ftp.example.org/example/example-0.0.2.tar.xz"
sha256 = ""

[build]
system = "make"

[scripts]
patch = "patch.sh"
build = "build.sh"
install = "install.sh"
check = "check.sh"
